<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>edfa31b1-c949-461e-b693-70da8bb4df7b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudioTranscriber.Application\AudioTranscriber.Application.csproj" />
    <ProjectReference Include="..\AudioTranscriber.Shared\AudioTranscriber.Shared.csproj" />
    <ProjectReference Include="..\AudioTranscriber.Infrastructure\AudioTranscriber.Infrastructure.csproj" />
  </ItemGroup>

</Project>
